#!/bin/bash
# Wrapper script to run pipeline.py using FreeCAD's Python interpreter
# Usage: ./run_pipeline.sh input.step [--out output.pdf] [other options]

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PIPELINE_PY="$SCRIPT_DIR/pipeline.py"

# Change to script directory so output/ is created there
cd "$SCRIPT_DIR"

# Load environment variables from .env file if it exists
if [ -f "$SCRIPT_DIR/.env" ]; then
    export $(cat "$SCRIPT_DIR/.env" | grep -v '^#' | xargs)
fi

# Check if FreeCAD is installed
FREECAD_CMD="/Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd"
if [ ! -f "$FREECAD_CMD" ]; then
    echo "Error: FreeCAD not found at $FREECAD_CMD"
    echo "Please install FreeCAD or update the path in this script"
    exit 1
fi

# Convert arguments to JSON format (handles Unicode properly)
ARGS_JSON=$(python3 -c "import sys, json; print(json.dumps(sys.argv[1:]))" "$@")

# Create temporary files for arguments and script
TEMP_ARGS_FILE=$(mktemp /tmp/pipeline_args_XXXXXX.json 2>/dev/null || echo /tmp/pipeline_args_$$.json)
TEMP_SCRIPT=$(mktemp /tmp/pipeline_runner_XXXXXX.py 2>/dev/null || echo /tmp/pipeline_runner_$$.py)

# Write arguments to file
echo "$ARGS_JSON" > "$TEMP_ARGS_FILE"

# Create the Python runner script
cat > "$TEMP_SCRIPT" << 'PYTHON_EOF'
# -*- coding: utf-8 -*-
import sys
import os
import json
import traceback

# Get paths from environment
SCRIPT_DIR = os.environ.get('PIPELINE_SCRIPT_DIR')
ARGS_FILE = os.environ.get('PIPELINE_ARGS_FILE')
PIPELINE_PY = os.path.join(SCRIPT_DIR, 'pipeline.py')

# Change to script directory
os.chdir(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

try:
    # Read arguments from JSON file
    with open(ARGS_FILE, 'r', encoding='utf-8') as f:
        args = json.load(f)
    sys.argv = ['pipeline.py'] + args
    
    # Execute pipeline.py
    # Set __file__ in globals so the script knows its location
    import builtins
    globals()['__file__'] = PIPELINE_PY
    globals()['__name__'] = '__main__'
    
    with open(PIPELINE_PY, 'r', encoding='utf-8') as f:
        code = compile(f.read(), PIPELINE_PY, 'exec')
        exec(code, globals())
except Exception as e:
    print(f"ERROR: Pipeline failed with exception: {e}", file=sys.stderr)
    traceback.print_exc(file=sys.stderr)
    sys.exit(1)
PYTHON_EOF

# Export environment variables
export PIPELINE_SCRIPT_DIR="$SCRIPT_DIR"
export PIPELINE_ARGS_FILE="$TEMP_ARGS_FILE"

# Use freecadcmd to execute the temporary script
# Redirect stderr to see any errors
"$FREECAD_CMD" "$TEMP_SCRIPT" 2>&1

EXIT_CODE=$?

# Extract output path from arguments for SVG->PDF conversion
OUTPUT_PATH=""
FOUND_OUT_FLAG=0
for arg in "$@"; do
    if [ "$FOUND_OUT_FLAG" = "1" ]; then
        # Previous argument was --out or -o, this is the value
        OUTPUT_PATH="$arg"
        FOUND_OUT_FLAG=0
        break
    elif [ "$arg" = "--out" ] || [ "$arg" = "-o" ]; then
        FOUND_OUT_FLAG=1
        continue
    elif [[ "$arg" == --out=* ]]; then
        OUTPUT_PATH="${arg#--out=}"
        break
    elif [[ "$arg" == -o=* ]]; then
        OUTPUT_PATH="${arg#-o=}"
        break
    fi
done

# If no explicit output path, determine default from first argument (input file)
if [ -z "$OUTPUT_PATH" ] && [ -n "$1" ]; then
    BASE_NAME=$(basename "$1" | sed 's/\.[^.]*$//')
    OUTPUT_PATH="output/$BASE_NAME"
fi

# If output path doesn't end with .pdf, it's a base name (will have .pdf appended)
PDF_PATH="$OUTPUT_PATH"
if [[ ! "$PDF_PATH" == *.pdf ]]; then
    PDF_PATH="$OUTPUT_PATH.pdf"
fi

# SVG path (same as PDF but with .svg extension)
SVG_PATH="${PDF_PATH%.pdf}.svg"

# Convert SVG to PDF if SVG exists and is not empty (Tier2 export)
if [ -f "$SVG_PATH" ] && [ -s "$SVG_PATH" ]; then
    echo "[Post-processing] Converting SVG to PDF..."
    
    # Try to convert SVG to PDF using system python3 with cairosvg
    if python3 -c "import cairosvg" 2>/dev/null; then
        if python3 <<PYEOF
import cairosvg
import sys
cairosvg.svg2pdf(url='$SVG_PATH', write_to='$PDF_PATH')
print(f"  [OK] Converted SVG -> PDF: $PDF_PATH")
PYEOF
        then
            # Conversion successful - remove temporary SVG file
            rm -f "$SVG_PATH"
        else
            echo "  [WARN] SVG->PDF conversion failed, keeping placeholder PDF if it exists"
        fi
    else
        echo "  [INFO] cairosvg not available in system python3 (install with: pip3 install cairosvg)"
        echo "  [INFO] Keeping placeholder PDF generated by Tier3 fallback"
    fi
fi

# Clean up temporary files
rm -f "$TEMP_SCRIPT" "$TEMP_ARGS_FILE"

exit $EXIT_CODE
